a = str("yayuk")
b = int(2001)
c = float(2.001)
d = complex(2001j)
e = list(("merden", "purwanegara", "banjarnegara"))
f = tuple(("central java", "indonesia", "southeast asia"))
g = range(30)
h = dict(name="yayuk", age=19)
i = set(("one", "two", "three"))
j = frozenset(("four", "five", "six"))
k = bool(60)
l = b"wakanda foreva"
m = bytearray(5)
n = memoryview(bytes(10))


#display all data
#complex can uses all number but alphabet onli j, l
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i) 
print(j)
print(k)
print(l) 
print(m)
print(n)

#display the data type
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(type(i))
print(type(j))
print(type(k))
print(type(l))
print(type(m))
print(type(n))
